[versions]
gradleAndroid = "8.0.0-alpha01"
# @pin
kotlin = "1.7.10"
koin = "3.2.2"
detekt = "1.22.0-RC1"
coroutines = "1.6.4"
lifecycle = "2.5.1"
flowExt = "0.3.0"
core-ktx = "1.9.0"
compose = "1.3.0-beta03"
kotest = "5.4.2"
mockk = "1.13.1"
turbine = "0.11.0"
junit = "4.13.2"
activity = "1.6.0"
material = "1.7.0-rc01"
fragment = "1.5.3"
detektFormattingPlugin = "1.22.0-RC1"
composeDetektPlugin = "1.2.1"
versionsPlugin = "0.42.0"
versionCatalogUpdatePlugin = "0.6.1"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleAndroid" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormattingPlugin" }
detekt-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "composeDetektPlugin" }
gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin" }
#core kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
flowext = { module = "io.github.hoc081098:FlowExt-jvm", version.ref = "flowExt" }
# androidx
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
#test
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
kotest-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
#di
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-compose = "io.insert-koin:koin-androidx-compose:3.2.1"
#compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }

[bundles]
unittest = [
    "koin-test",
    "kotest-assertions",
    "kotest-junit",
    "kotest-property",
    "kotlin-reflect",
    "mockk",
    "mockk-jvm",
    "turbine",
]
koin = [
    "koin-android",
    "koin-core",
]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
