name: Ask a question
title: "❔: "
description: Ask a question, request documentation, or something else
labels: [ triage ]
assignees: [ Nek-12 ]
type: 'task'
body:
  - type: textarea
    attributes:
      label: Description
      description: What do you want to know?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Before you submit
      options:
        - label: 'I have read the FAQ and documentation'
          required: true
        - label: 'I have used search to see if this question has already been answered'
          required: true
