[versions]
decompose = "3.0.0"
apiresult = "1.0.4"
koin = "3.6.0-wasm-alpha2"
kmputils = "1.3.2"
material = "1.12.0"
activity = "1.9.0"
okio = "3.9.0"
splashscreen = "1.1.0-rc01"
xml-constraintlayout = "2.2.0-alpha13"
codehighlights = "0.9.0"

[libraries]
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

kmputils-common = { module = "pro.respawn.kmmutils:common", version.ref = "kmputils" }
kmputils-coroutines = { module = "pro.respawn.kmmutils:coroutines", version.ref = "kmputils" }
kmputils-datetime = { module = "pro.respawn.kmmutils:datetime", version.ref = "kmputils" }
kmputils-inputforms = { module = "pro.respawn.kmmutils:inputforms", version.ref = "kmputils" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
okio-fakefsys = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
apiresult = { module = "pro.respawn.apiresult:core", version.ref = "apiresult" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
view-material = { module = "com.google.android.material:material", version.ref = "material" }
view-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "xml-constraintlayout" }
compose-codehighlighting = { module = "dev.snipme:highlights", version.ref = "codehighlights" }

[bundles]
koin = [
    "koin-compose",
    "koin-core",
]
kmputils = [
    "kmputils-common",
    "kmputils-coroutines",
    "kmputils-datetime",
    "kmputils-inputforms",
]

[plugins]
android-application = { id = "com.android.application" }
