name: publish

on:
  push:
    tags:
      - '2.*'

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-latest
    environment: publishing

    steps:
      - uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 21
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Publish to sonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        # It's important to not upload in parallel or duplicate repos will be created
        # repository creds are broken with gradle 8.6 https://github.com/gradle/gradle/issues/24040
        run: ./gradlew publishAllPublicationsToSonatypeRepository -Dorg.gradle.parallel=false --stacktrace --no-configuration-cache
