name: publish

on:
  push:
    tags:
      - '2.*'

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 21
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > local.properties

      - name: Create macOS debugger distributable
        run: ./gradlew debugger:app:packageDistributionForCurrentOS

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Debugger_MacOS
          path: ./debugger/app/build/compose/binaries/main/dmg/*
          if-no-files-found: error
          overwrite: true

      - name: Publish to sonatype
        env:
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          # It's important to not upload in parallel or duplicate repos will be created
        run: ./gradlew publishAllPublicationsToSonatypeRepository -Dorg.gradle.parallel=false --stacktrace
